---
- hosts: [lab]
  vars:
        zbxserver : '192.168.2.131'
        listenport : '10055'
        hostname : 'bp.{{hip.stdout}}'

  tasks:
      #Verificações do S.O
      - name: "Nome da maquina"
        shell: hostname | tr 'A-Z' 'a-z'
        register: hname

      - name: "IP"
        shell: hostname -I | awk '{print $2}'
        register: hip

      #Instala repositorio zabbix
      - name: "Instala repositorio zabbix 5 Debian"
        apt:
            deb: https://repo.zabbix.com/zabbix/5.0/{{ansible_distribution}}/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ansible_distribution_version}}_all.deb
            force: yes
            state: present
        become: yes
        when: (ansible_os_family == "Debian" or ansible_os_family == "Ubuntu")

      - name: "Instala o repositorio do zabbix 5 RedHat"
        yum:
            name: "https://repo.zabbix.com/zabbix/5.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-5.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
            state: present
            validate_certs: no
        become: yes
        when: (ansible_distribution == "RedHat")

      #Atualizando os pacotes
      - name: "Atualiza os pacotes Delian"
        apt:
          upgrade: no
          update_cache: yes
          cache_valid_time: 86400 #One day
        become: yes
        when: (ansible_os_family == "Debian" or ansible_os_family == "Ubuntu")

      - name: "Atualiza os pacotes RedHat até versão 7"
        become: yes
        shell: yum clean all
        when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")

      - name: "Atualiza os pacotes RedHat a partir versão 8"
        become: yes
        shell: dnf clean all
        when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8")

      #Instalação do zabbix agent
      - name: "Install agent-zabbix 2 Debian"
        apt:
          name: zabbix-agent2
          state: present
        when: (ansible_os_family == "Debian" or ansible_os_family == "Ubuntu")
        become: yes

      - name: "Install agent-zabbix 2 RedHat < 7"
        yum:
          name: zabbix-agent2
          state: present
        when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")
        become: yes

      - name: "Install agent-zabbix 2 RedHat > 7"
        dnf:
          name: zabbix-agent2
          state: present
        when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8")
        become: yes

      #Altera arquivo zabbix agent2 com novos parametros
      - name: "Altera arquivo zabbix.agent2.conf"
        replace:
            path: /etc/zabbix/zabbix_agent2.conf
            regexp: "{{ item.regex }}"
            replace: "{{ item.value }}"
        with_items:
            - { regex: '^\#\ ListenPort\=10050$', value: 'ListenPort={{listenport}}' }
            - { regex: '^Server\=127\.0\.0\.1$', value: 'Server={{zbxserver}}' }
            - { regex: '^ServerActive\=127\.0\.0\.1$', value: 'ServerActive={{zbxserver}}' }
            - { regex: '^Hostname\=Zabbix server$', value: 'Hostname=bp-aws.app.prd.v.{{hip.stdout}}' }
            #- { regex: '^Hostname\=Zabbix server$', value: 'Hostname={{hostname}}' }
            #{ regex: '^\#HostnameItem\=system\.hostname$', value: 'HostnameItem=system.hostname' }
        become: yes

      #Adiciona na inicilização
      - name: "Adiciona o serviço do zabbix agent2 para inicialização automatica e reinicia o serviço"
        ansible.builtin.service:
              name: zabbix-agent2
              state: restarted
              enabled: yes
        become: yes
