---
#Validações SO
- name: Variavel de sistema operacional
  shell: lsb_release -si | tr 'A-Z' 'a-z'
  register: SO
  when: ansible_os_family == "Debian"

- name: Variavel da versao do sistema operacional Debian like
  shell: lsb_release -sc
  register: SOVERSIONDEB
  when: ansible_os_family == "Debian"

- name: Variavel da versao do sistema operacional RedHat like
  shell: lsb_release -sc
  register: SOVERSIONEL
  when: ansible_os_family == "RedHat"

- name: Variavel do nome da maquina
  shell: hostname | tr 'A-Z' 'a-z'
  register: hname

- name: Variavel IP
  shell: hostname -I | awk '{print $1}'
  register: hip

#Baixando biblioteca zabbix
- name: Baixar biblioteca Zabbix-Agent 5.0 Debian Like
  apt:
      deb: https://repo.zabbix.com/zabbix/5.0/"{{ SO.stdout }}"/pool/main/z/zabbix-release/zabbix-release_5.0-1+"{{ SOVERSIONDEB.stdout }}"_all.deb
  become: yes
  when: ansible_os_family == "Debian"

- name: Baixar biblioteca Zabbix-Agent 5.0 RedHat até versão 7
  yum:
       rpm: https://repo.zabbix.com/zabbix/5.0/rhel/"{{ SOVERSIONEL.stdout }}"/x86_64/zabbix-release-5.0-1.el"{{ SOVERSIONEL.stdout }}".noarch.rpm
  become: yes
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")

- name: Baixar biblioteca Zabbix-Agent 5.0 RedHat apatir versão 8
  dnf:
       rpm: https://repo.zabbix.com/zabbix/5.0/rhel/"{{ SOVERSIONEL.stdout }}"/x86_64/zabbix-release-5.0-1.el"{{ SOVERSIONEL.stdout }}".noarch.rpm
  become: yes
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version => "8")

#Atualizando os pacotes
- name: Atualiza os pacotes Delian like
  apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: yes
  when: ansible_os_family == "Debian"

- name: Atualiza os pacotes RedHat até versão 7
  become: yes
  shell: yum clean all
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")

- name: Atualiza os pacotes RedHat a partir versão 8
  become: yes
  shell: dnf clean all
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")

#Instalação do zabbix agent
- name: Install agent-zabbix 2 Debian Like
  apt:
    name: zabbix-agent2
    state: present
  when: ansible_os_family == "Debian"

- name: Install agent-zabbix 2 RedHat < 7 Like
  yum:
    name: zabbix-agent2
    state: present
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")

- name: Install agent-zabbix 2 RedHat > 7  Like
  dnf:
    name: zabbix-agent2
    state: present
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version => "8")

#Altera arquivo zabbix agent2 com novos parametros
- name: 'Altera arquivo zabbix.agent2.conf'
  replace:
       path: /etc/zabbix/zabbix_agent2.conf
       regexp: "{{ item.regex }}"
       replace: "{{ item.value }}"
  with_items:
      - { regex: '^Server\=127\.0\.0\.1$', value: 'Server=192.168.2.145' }
      - { regex: '^ServerActive\=127\.0\.0\.1$', value: 'ServerActive=192.168.2.145' }
      - { regex: '^Hostname\=Zabbix server$', value: 'Hostname="{{hname.stdout}}"' }
      #{ regex: '^\#HostnameItem\=system\.hostname$', value: 'HostnameItem=system.hostname' }
  become: yes

#Reinicia o serviço
- name: 'Reinicia o serviço do zabbix agent'
  ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
        enabled: yes
  become: yes