---
- hosts: [FRU]
  tasks:

   - name: 'Instala repositorio zabbix .deb da internet'
     apt:
      deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb
     become: yes

   - name: 'Atualiza os pacotes'
     become: true
     apt:
      upgrade: no
      update_cache: yes
      cache_valid_time: 86400 #One day

   - name: 'Instala zabbix agent'
     apt:
       name:
       - zabbix-agent
       state: present 
     become: yes

   - name: 'Altera arquivo zabbix.agentd.conf'
     replace:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: "{{ item.regex }}"
       replace: "{{ item.value }}"
     with_items:
        - { regex: '^Server\=127\.0\.0\.1$', value: 'Server=192.168.2.145' }
        - { regex: '^ServerActive\=127\.0\.0\.1$', value: 'ServerActive=192.168.2.145' }
        - { regex: '^Hostname\=Zabbix server$', value: '#Hostname=Zabbix server' }
        - { regex: '^\#HostnameItem\=system\.hostname$', value: 'HostnameItem=system.hostname' }
     become: yes

   - name: 'Reinicia o serviço do zabbix agent'
     ansible.builtin.service:
        name: zabbix-agent
        state: restarted
     become: yes
      


  # - name: 'Instala php7.2'
  #   apt:
  #       name: php7.2
  #       state: latest
  #   become: yes
  # - name: 'Instala apache2'
  #   apt:
  #       name: apache2
  #       state: latest
  #   become: yes
  # - name: 'Instala modphp'
    # apt:
    #     name: libapache2-mod-php7.2
    #     state: latest
    # become: yes









  #    - name: 'Instala pacote zabbix .deb da internet'
  #   apt:
  #     deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu14.04_all.deb

  #  - name: 'Atualiza os pacotes'
  #    become: true
  #    apt:
  #     upgrade: no
  #     update_cache: yes
  #     cache_valid_time: 86400 #One day

  #  - name: 'Instala pacotes de dependencia do sistema operacional'
  #    apt:
  #      name:
  #      - php7.2
  #      - apache2
  #      - libapache2-mod-php7.2
  #      - php7.2-gd
  #      - libssh2-1
  #      - php-horde-crypt-blowfish
  #      - mysql-server
  #      - python-mysqldb
  #      - php7.2-mysql
  #      state: latest 
  #    become: yes


  #  - name: 'Cria banco do mysql'
  #    mysql_db:
  #      name: wordpress_db
  #      login_user: root
  #      login_password: root
  #      state: present

